# Generated by Django 5.0.14 on 2026-08-09 11:39

import common.uploads
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nom')),
                ('normalized_name', models.CharField(editable=False, max_length=120)),
                ('uploaded_image', models.ImageField(blank=True, null=True, upload_to=common.uploads.item_image_upload_to, verbose_name='image uploadée')),
                ('external_image_url', models.URLField(blank=True, max_length=500, verbose_name='image distante')),
                ('joker_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'item',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TierList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nom')),
                ('theme', models.CharField(max_length=120, verbose_name='thème')),
                ('invite_code', models.CharField(db_index=True, max_length=6, unique=True, verbose_name="code d'invitation")),
                ('status', models.CharField(choices=[('DRAFT', 'En création'), ('ANSWERING', 'Questionnaire en cours'), ('JOKER', 'Phase joker'), ('COMPLETED', 'Terminée')], db_index=True, default='DRAFT', max_length=12, verbose_name='statut')),
                ('rank_1_name', models.CharField(default='S', max_length=30, verbose_name='rang 1')),
                ('rank_2_name', models.CharField(default='A', max_length=30, verbose_name='rang 2')),
                ('rank_3_name', models.CharField(default='B', max_length=30, verbose_name='rang 3')),
                ('rank_4_name', models.CharField(default='C', max_length=30, verbose_name='rang 4')),
                ('rank_5_name', models.CharField(default='D', max_length=30, verbose_name='rang 5')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tier_lists', to=settings.AUTH_USER_MODEL, verbose_name='créateur')),
            ],
            options={
                'verbose_name': 'Tier List',
                'verbose_name_plural': 'Tier Lists',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=300, verbose_name='affirmation')),
                ('coefficient', models.PositiveSmallIntegerField(verbose_name='coefficient')),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tier_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tierlists.tierlist')),
            ],
            options={
                'verbose_name': 'question',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ItemScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_score', models.DecimalField(decimal_places=10, max_digits=16)),
                ('algorithm_rank', models.PositiveSmallIntegerField()),
                ('current_rank', models.PositiveSmallIntegerField()),
                ('final_rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='tierlists.item')),
                ('tier_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='tierlists.tierlist')),
            ],
            options={
                'verbose_name': "score d'item",
                'verbose_name_plural': "scores d'items",
                'ordering': ['-global_score', 'item_id'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='tier_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tierlists.tierlist'),
        ),
        migrations.CreateModel(
            name='TierListParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('answering_started_at', models.DateTimeField(blank=True, null=True)),
                ('answering_completed_at', models.DateTimeField(blank=True, null=True)),
                ('answer_order_seed', models.BigIntegerField(default=0)),
                ('joker_order', models.PositiveIntegerField(blank=True, null=True)),
                ('tier_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tierlists.tierlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'participant',
                'ordering': ['joined_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ParticipantItemProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField()),
                ('is_validated', models.BooleanField(default=False)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_progress', to='tierlists.item')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_progress', to='tierlists.tierlistparticipant')),
            ],
            options={
                'verbose_name': 'progression item',
                'verbose_name_plural': 'progressions item',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='JokerAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('to_rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('USED', 'Utilisé'), ('SKIPPED', 'Abandonné'), ('FORCED_SKIP', 'Tour forcé par le créateur')], default='PENDING', max_length=12)),
                ('played_at', models.DateTimeField(blank=True, null=True)),
                ('forced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forced_jokers', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joker_actions', to='tierlists.item')),
                ('tier_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joker_actions', to='tierlists.tierlist')),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='joker', to='tierlists.tierlistparticipant')),
            ],
            options={
                'verbose_name': 'joker',
                'ordering': ['participant__joker_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(verbose_name='valeur')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tierlists.item')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tierlists.question')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tierlists.tierlistparticipant')),
            ],
            options={
                'verbose_name': 'réponse',
            },
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(check=models.Q(('coefficient__in', (1, 2, 3, 5))), name='question_coefficient_allowed'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('tier_list', 'normalized_name'), name='unique_item_name_per_tier_list'),
        ),
        migrations.AddConstraint(
            model_name='tierlistparticipant',
            constraint=models.UniqueConstraint(fields=('tier_list', 'user'), name='unique_participant_per_tier_list'),
        ),
        migrations.AddConstraint(
            model_name='participantitemprogress',
            constraint=models.UniqueConstraint(fields=('participant', 'item'), name='unique_progress_per_participant_item'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('participant', 'item', 'question'), name='unique_answer_per_cell'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.CheckConstraint(check=models.Q(('value__gte', 1), ('value__lte', 9)), name='answer_value_between_1_and_9'),
        ),
    ]
